# Import libraries

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="white")
import warnings
warnings.filterwarnings("ignore")

# Import dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/philsaurabh/Machine-Learning-Tutorials/main/Telco_Customer_Churn.csv')

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.shape

(7043, 21)

In [5]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [6]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [7]:
df.describe

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DS

In [8]:
df['TotalCharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

# Data Cleaning and Preprocessing

In [9]:
df.isnull().sum().sum()

0

In [11]:

print ('Churn Percentages are\n',df.Churn.value_counts() / df.Churn.count())

Churn Percentages are
 No     0.73463
Yes    0.26537
Name: Churn, dtype: float64


In [34]:
df['Churn'].replace(to_replace ='Yes', value=1, inplace=True)
df['Churn'].replace(to_replace = 'No', value=0, inplace=True)
df = pd.get_dummies(df)

In [14]:
df.head()

SeniorCitizen  tenure  MonthlyCharges  Churn  gender_Female  gender_Male  \
0              0       1           29.85      0              1            0   
1              0      34           56.95      0              0            1   
2              0       2           53.85      1              0            1   
3              0      45           42.30      0              0            1   
4              0       2           70.70      1              1            0   

   Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  ...  \
0           0            1              1               0  ...   
1           1            0              1               0  ...   
2           1            0              1               0  ...   
3           1            0              1               0  ...   
4           1            0              1               0  ...   

   TotalCharges_995.35  TotalCharges_996.45  TotalCharges_996.85  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   TotalCharges_996.95  TotalCharges_997.65  TotalCharges_997.75  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   TotalCharges_998.1  TotalCharges_999.45  TotalCharges_999.8  \
0                   0                    0                   0   
1                   0                    0                   0   
2                   0                    0                   0   
3                   0                    0                   0   
4                   0                    0                   0   

   TotalCharges_999.9  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 6576 columns]

In [15]:
df.isnull().sum().sum()

0

In [16]:
df = df.dropna()

In [17]:
df.isnull().sum().sum()

0

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, ConfusionMatrixDisplay, precision_score, recall_score, f1_score, classification_report, roc_curve, auc, precision_recall_curve, average_precision_score
from sklearn.model_selection import cross_val_score

In [21]:
X = df.drop(columns = ['Churn'])
y = df['Churn'].values

In [22]:
y

array([0, 0, 1, ..., 0, 1, 0])

In [23]:
Scaler = StandardScaler()
X = Scaler.fit_transform(X)

In [24]:
X

array([[-0.43991649, -1.27744458, -1.16032292, ..., -0.01191659,
        -0.01191659, -0.01191659],
       [-0.43991649,  0.06632742, -0.25962894, ..., -0.01191659,
        -0.01191659, -0.01191659],
       [-0.43991649, -1.23672422, -0.36266036, ..., -0.01191659,
        -0.01191659, -0.01191659],
       ...,
       [-0.43991649, -0.87024095, -1.1686319 , ..., -0.01191659,
        -0.01191659, -0.01191659],
       [ 2.27315869, -1.15528349,  0.32033821, ..., -0.01191659,
        -0.01191659, -0.01191659],
       [-0.43991649,  1.36937906,  1.35896134, ..., -0.01191659,
        -0.01191659, -0.01191659]])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5634, 6575), (1409, 6575), (5634,), (1409,))

In [27]:
model = LogisticRegression()#KNeighborsClassifier()#SVC#RandomForestClassifier()#AdaBoostClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = cross_val_score(model, X_train, y_train, cv = 6)
precision = precision_score(y_test, y_pred)
roc = roc_auc_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print ('Train score of '+str(model)[:-2]+' is', score.mean(),'%')
print ('--')
print ('Precision score is ', precision)
print ('--')
print ('ROC Score is', roc)
print ('--')
print ('Recall Score is ', recall)
print ('--')
print ('Confusion Matrix\n\n', cm)

Train score of LogisticRegression is 0.7669506567270146 %
--
Precision score is  0.5842696629213483
--
ROC Score is 0.7073918039065492
--
Recall Score is  0.5576407506702413
--
Confusion Matrix

 [[888 148]
 [165 208]]


In [28]:
#HoldOut Validation Approach- Train And Test Split
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result = model.score(X_test, y_test)
print(result)
#K Fold Cross Validation
from sklearn.model_selection import KFold
model=DecisionTreeClassifier()
kfold_validation=KFold(10)

from sklearn.model_selection import cross_val_score
results=cross_val_score(model,X,y,cv=kfold_validation)
print(results)
print(np.mean(results))

0.7693399574166075
[0.77446809 0.76453901 0.75602837 0.78693182 0.77130682 0.75
 0.76278409 0.74431818 0.78977273 0.78267045]
0.7682819551901998


In [29]:
from sklearn.model_selection import StratifiedKFold
skfold=StratifiedKFold(n_splits=5)
model=DecisionTreeClassifier()
scores=cross_val_score(model,X,y,cv=skfold)
print(np.mean(scores))

0.7630287639525131


In [30]:
scores

array([0.76863023, 0.75514549, 0.75372605, 0.76846591, 0.76917614])

In [31]:
from sklearn.model_selection import ShuffleSplit
model=DecisionTreeClassifier()
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
results=cross_val_score(model,X,y,cv=ssplit)

In [32]:
results

array([0.78655939, 0.77756744, 0.77425461, 0.76289636, 0.77141505,
       0.77662092, 0.76573592, 0.77188831, 0.77046853, 0.77188831])

In [33]:
np.mean(results)

0.7729294841457642